[package]
name = "reqwest-websocket"
version = "0.1.0"
edition = "2021"
authors = ["Janosch Gräf <janosch.graef@gmail.com>"]
description = "Websocket connections with reqwest"
readme = "README.md"
homepage = "https://github.com/jgraef/reqwest-websocket"
repository = "https://github.com/jgraef/reqwest-websocket"
license = "MIT"
keywords = ["websocket", "reqwest", "stream"]
categories = ["network-programming", "web-programming::http-client", "web-programming::websocket"]

[dependencies]
async-tungstenite = { version = "0.25.0", default-features = false }
futures-util = { version = "0.3.30", default-features = false }
reqwest = { version = "0.11.24", default-features = false }
thiserror = "1.0.57"
tokio-util = { version = "0.7.10", default-features = false, features = ["compat"] }
tracing = "0.1.40"
tungstenite = { version = "0.21.0", default-features = false, features = ["handshake"] }

[dev-dependencies]
tokio = { version = "1.36.0", features = ["macros", "rt-multi-thread"] }
reqwest = { version = "0.11.24", features = ["default-tls"] }
